/*
 * @lc app=leetcode.cn id=1366 lang=javascript
 * @lcpr version=30204
 *
 * [1366] 通过投票对团队排名
 */


// @lcpr-template-start

// @lcpr-template-end
// @lc code=start
/**
 * @param {string[]} votes
 * @return {string}
 */
var rankTeams = function(votes) {
  if (votes.length === 1) return votes[0];

  const teamRanks = new Map();
  for (const vote of votes) {
    for (let i = 0; i < vote.length; i++) {
      if (!teamRanks.has(vote[i])) teamRanks.set(vote[i], new Array(26).fill(1000));

      const ranks = teamRanks.get(vote[i]);
      ranks[i]--;
    }
  }

  return [...teamRanks].map(([team, ranks]) => [ranks.map((rank) => rank.toString().padStart(4, '0')), team]).sort().map(([_ranks, team]) => team).join('');
};
// @lc code=end



// @lcpr case=start
// ["ABC","ACB","ABC","ACB","ACB"]\n
// @lcpr case=end

// @lcpr case=start
// ["WXYZ","XYZW"]\n
// @lcpr case=end

// @lcpr case=start
// ["ZMNAGUEDSJYLBOPHRQICWFXTVK"]\n
// @lcpr case=end

// @lcpr case=start
// ["AB","BA"]\n
// @lcpr case=end

// @lcpr case=start
// ["ABCDEFGHIJKLMNOPQRSTUVWXYZ","ZYXWVUTSRQPONMLKJIHGFEDCBA"]\n
// @lcpr case=end

// @lcpr case=start
// ["ZCJRXQMNIT","TRZJQNCMIX","ZRTXIJQMNC","MTCJZQRNXI","IMTCRQZXNJ","TXIMCQJZNR","NJQIRXMZTC","ZMXRTINJQC","NJMICXZQRT","JMTRNQIXCZ","ZJNIXMQTCR","TXNZMJQRCI","QMXITJRNZC","MNTRQIZCXJ","RCQXMZINJT","RQJNMTICXZ","ZRJNQCMIXT","MXNZQJTRIC","TQIRXNCJMZ","XMCJQTZRNI","ZRNJIQXCTM","MRZCXTQIJN","XMIQJNZCRT","RXTMQZJNIC","QXZMCINRTJ","RXCTJMZNQI","MZXJTIRNCQ","INZRTXJQCM","MQRZTXCNIJ","MNZITXCRJQ","IMNTXQRZCJ","MRNZITXQJC","NCITXMRJZQ","CTRIMNQXJZ","QZNXJIRTCM","JXCTRZQINM","MIZXNQRTCJ","TNQCIMRZXJ","XJZRNTMQIC","QNRMJXCTZI","NMXRTQJZCI","CINRZTXMJQ","QMRCZTXNJI","ZMRXJCTIQN","RIZNMXQJTC","MQNXRCTIJZ","JCMTRINXZQ","XZRMQITCJN","CJRQTZIMNX","RCJXZQMNTI","XTJMQIZRCN","TIZJMRQCNX","MTZQNJRXCI","XZNRJQCTMI","CNJITZXRMQ","XRNTCJQZMI","TNQCRXIJMZ","ZITMXCQNJR","ZJIXTCMNQR","TZJRICMXQN","IQXMJNZTRC","CJQZMTRINX","JTXNMRQCIZ","ZMXQTCIJRN","QRIJTMCXZN","ZNMJIRQXCT","MIQJTRZXNC","TQRNJXZMIC","MTQICNJRXZ","RJCZXMITQN","RTCINZJQXM","TJNCXMIQZR","CQRIJZXNMT","NCXMIRTQJZ","TIZMNJXRQC","XMQRTZICNJ","QMNZRIXCTJ","JNZMIRXTCQ","NRIXCTZJQM","TQXNRZCJIM","NCXRJZTMQI","TXZRCMNQJI","MTXZCQINRJ","MICRTXNQJZ","JMIQXTNCZR","NZRCMXJQIT","MTIJCXRZNQ","IMCNTJZXRQ","NXTQJRZCIM","ZCMTIXRNJQ","TMJNQZCIRX","TQIMJZNXRC","ZTRJXNMIQC","IMXZRQCNJT","NIJZTMRCXQ","XTINJRZCQM","NTZRJMIQCX","RZCINXMQTJ","RXJINZQCTM","QIRTZNMCJX","XQICZTRMNJ","IXZRCTJQMN","ZXMCJRQTNI","JIQCRNXZMT","IQRXCTJMZN","ZRJMQCTXNI","RJNXIQZTCM","ZNIQXMCTRJ","RCIZQTMNXJ","QRNXZMJITC","JCZXINTQMR","CJXITQZNMR","NIJZRXTQCM","CIXJQTZNMR","NJMCIXTRZQ","JXRCMTZQIN","JCTQMNRIZX","CMZJNXQRIT","XJCNQTMIRZ","XMITRJCQNZ","CMZTIXNJRQ","XMQJINTCZR","TCJXZNRMQI","ZQCNXTJRMI","CINMQJXZRT","MJXRNCTIZQ","JRTCZXIQMN","NMTZXCQIRJ","RNQMZJITCX","TQJIZMXCRN","CZTXMQIJNR","JXQZITCRMN","XRIJMTZQCN","QCTNJIXZMR","NTQCIZXMJR","JNZXRQTCMI","XRCTMQZIJN","IZXTMCQRJN","RIJMCZQNTX","RTCNJIXQMZ","ZICMJQXRTN","MCXIQZNRJT","QMNRJXZICT","TQXMNIJCRZ","IQRNJTXZCM","IXCZNJQRMT","QXTMZCRNJI","CIRJZXQTMN","TNMRJCZXIQ","ZNCITMQRJX","RNXICQJZTM","CZQRNTXMJI","NTXZQJIMCR","IMQCXTJNZR","ZNTRJQCXIM","ZMXRJNITCQ","QXMTRZNCIJ","CQXRZIMJTN","XZINCQJRMT","RQNIXTZCMJ","NCZRITJMXQ","JMXRZQNICT","XJQNZIRTMC","QMRJZXNTIC","ZJTNRQIXMC","XJIZNMCQRT","JXMIQRNZCT","NITMQZCRJX","XZNTRJMQCI","NQCZMJIXRT","QTZICNJXMR","QIZTCXNRMJ","ZJRIXMCTNQ","JMZXCNRQIT","IMNRCTXJZQ","QTCMZRNXIJ","TRIXMZJCNQ","IJXTQNZMCR","RZNJCIMXTQ","NZJTIRCQXM","RNQMXCZTIJ","TZRXCINQMJ","CNIQJMTXRZ","ZJMRXCNIQT","JIXZMTRQNC","RXQZNJMTCI","RXCTZMIJQN","QMJRZNITXC","NTJRICQMZX","JNRMZCQXIT","MZCTIJRNXQ","TJXIRMNQCZ","ITZJQCNMXR","RXQMJITZCN","NMQRJXCITZ","XRCMZQNTJI","RNITZJMQXC","CTZQRXJNIM","ZCJTQIXNMR","RICTZJMQNX","MZNXIQTCJR","JTRNZMXQIC","ICTZXMQNJR","JCTINZMXRQ","IMQCXNZRTJ","XZJMTCQRNI","NIXZMCJRTQ","CJTRIMZQNX","TIXJMNRCQZ","MCNXQZJRIT","QTZNXRCMJI","XTQIZMCRNJ","ZTJMQRCNIX","NCITZXRMQJ","QCTZXRNJIM","NMICXJQZRT","TJCNMZXIQR","RMCQTIZJNX","ZNMRICXQTJ","RIXQCJZTNM","INXRJZMCQT","MZJXTRQNIC","CJRNZQXTIM","NIRMZCTQJX","RMJQTICZNX","CJIMNZXQRT","JRMIZTNQXC","MIZCNRTXQJ","IJXRMCQZTN","NXZCQTJRMI","ZJTCRMQNXI","CRMQZNTJXI","JZMNTRXQCI","ICNRTMXZJQ","MCINRJQTZX","JRNIZQMCTX","CIQJRZXTMN","IXMNQCTJRZ","ZNJIRQXCTM","NJIRTMXCZQ","XTMJNRZCQI","JIXZMTNCRQ","RZNICJXTQM","JNMXZTQICR","NZXICQJMTR","TXJIZRCMQN","TCJINZMXQR","IXRJCQTZMN","NQMJRTICXZ","RMNXQJTZIC","NJQTZIMXCR","RIJMCQTZXN","CMQTZRNIXJ","QRMCTNZJIX","NMRZJCQTXI","IRNJXTMQCZ","MNTXJQZCIR","RXJIZQTNCM","IZCRTJNQXM","NQJMXITCRZ","XINMQRCJZT","MTNXCQRIJZ","ZTNRXIJMCQ","ITXZCQJNMR","XMJTIRQNCZ","JQTMRCIZXN","NMZCJQRXTI","ZTJNXMRQIC","NMRCTZQXJI","IJNQRXCTZM"]\n
// @lcpr case=end
